<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class KhUsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'admin',
                'email' => 'admin@example.com',
                'fullname' => 'Admin User',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user1',
                'email' => 'user1@example.com',
                'fullname' => 'User One',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user2',
                'email' => 'user2@example.com',
                'fullname' => 'User Two',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user3',
                'email' => 'user3@example.com',
                'fullname' => 'User Three',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user4',
                'email' => 'user4@example.com',
                'fullname' => 'User Four',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user5',
                'email' => 'user5@example.com',
                'fullname' => 'User Five',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user6',
                'email' => 'user6@example.com',
                'fullname' => 'User Six',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user7',
                'email' => 'user7@example.com',
                'fullname' => 'User Seven',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user8',
                'email' => 'user8@example.com',
                'fullname' => 'User Eight',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user9',
                'email' => 'user9@example.com',
                'fullname' => 'User Nine',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user10',
                'email' => 'user10@example.com',
                'fullname' => 'User Ten',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user11',
                'email' => 'user11@example.com',
                'fullname' => 'User Eleven',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user12',
                'email' => 'user12@example.com',
                'fullname' => 'User Twelve',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user13',
                'email' => 'user13@example.com',
                'fullname' => 'User Thirteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user14',
                'email' => 'user14@example.com',
                'fullname' => 'User Fourteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user15',
                'email' => 'user15@example.com',
                'fullname' => 'User Fifteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user16',
                'email' => 'user16@example.com',
                'fullname' => 'User Sixteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user17',
                'email' => 'user17@example.com',
                'fullname' => 'User Seventeen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user18',
                'email' => 'user18@example.com',
                'fullname' => 'User Eighteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user19',
                'email' => 'user19@example.com',
                'fullname' => 'User Nineteen',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user20',
                'email' => 'user20@example.com',
                'fullname' => 'User Twenty',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user21',
                'email' => 'user21@example.com',
                'fullname' => 'User Twenty-One',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user22',
                'email' => 'user22@example.com',
                'fullname' => 'User Twenty-Two',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'user23',
                'email' => 'user23@example.com',
                'fullname' => 'User Twenty-Three',
                'image_path' => null,
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
