<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => 'SP001',
                'name' => 'Product 1',
                'description' => 'Description for Product 1',
                'price' => 100.00,
                'image_path' => 'images/upload/products/1.jpg',
                'brand' => 'Brand 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP002',
                'name' => 'Product 2',
                'description' => 'Description for Product 2',
                'price' => 200.00,
                'image_path' => 'images/upload/products/2.jpg',
                'brand' => 'Brand 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP003',
                'name' => 'Product 3',
                'description' => 'Description for Product 3',
                'price' => 300.00,
                'image_path' => 'images/upload/products/3.jpg',
                'brand' => 'Brand 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP004',
                'name' => 'Product 4',
                'description' => 'Description for Product 4',
                'price' => 400.00,
                'image_path' => 'images/upload/products/4.jpg',
                'brand' => 'Brand 4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP005',
                'name' => 'Product 5',
                'description' => 'Description for Product 5',
                'price' => 500.00,
                'image_path' => 'images/upload/products/5.jpg',
                'brand' => 'Brand 5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP006',
                'name' => 'Product 6',
                'description' => 'Description for Product 6',
                'price' => 600.00,
                'image_path' => 'images/upload/products/6.jpg',
                'brand' => 'Brand 6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP007',
                'name' => 'Product 7',
                'description' => 'Description for Product 7',
                'price' => 700.00,
                'image_path' => 'images/upload/products/7.jpg',
                'brand' => 'Brand 7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP008',
                'name' => 'Product 8',
                'description' => 'Description for Product 8',
                'price' => 800.00,
                'image_path' => 'images/upload/products/8.jpg',
                'brand' => 'Brand 8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP009',
                'name' => 'Product 9',
                'description' => 'Description for Product 9',
                'price' => 900.00,
                'image_path' => 'images/upload/products/9.jpg',
                'brand' => 'Brand 9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP010',
                'name' => 'Product 10',
                'description' => 'Description for Product 10',
                'price' => 1000.00,
                'image_path' => 'images/upload/products/10.jpg',
                'brand' => 'Brand 10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP011',
                'name' => 'Product 11',
                'description' => 'Description for Product 11',
                'price' => 1100.00,
                'image_path' => 'images/upload/products/11.jpg',
                'brand' => 'Brand 11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP012',
                'name' => 'Product 12',
                'description' => 'Description for Product 12',
                'price' => 1200.00,
                'image_path' => 'images/upload/products/12.jpg',
                'brand' => 'Brand 12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP013',
                'name' => 'Product 13',
                'description' => 'Description for Product 13',
                'price' => 1300.00,
                'image_path' => 'images/upload/products/13.jpg',
                'brand' => 'Brand 13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP014',
                'name' => 'Product 14',
                'description' => 'Description for Product 14',
                'price' => 1400.00,
                'image_path' => 'images/upload/products/14.jpg',
                'brand' => 'Brand 14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP015',
                'name' => 'Product 15',
                'description' => 'Description for Product 15',
                'price' => 1500.00,
                'image_path' => 'images/upload/products/15.jpg',
                'brand' => 'Brand 15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP016',
                'name' => 'Product 16',
                'description' => 'Description for Product 16',
                'price' => 1600.00,
                'image_path' => 'images/upload/products/16.jpg',
                'brand' => 'Brand 16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP017',
                'name' => 'Product 17',
                'description' => 'Description for Product 17',
                'price' => 1700.00,
                'image_path' => 'images/upload/products/17.jpg',
                'brand' => 'Brand 17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP018',
                'name' => 'Product 18',
                'description' => 'Description for Product 18',
                'price' => 1800.00,
                'image_path' => 'images/upload/products/18.jpg',
                'brand' => 'Brand 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP019',
                'name' => 'Product 19',
                'description' => 'Description for Product 19',
                'price' => 1900.00,
                'image_path' => 'images/upload/products/19.jpg',
                'brand' => 'Brand 19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'SP020',
                'name' => 'Product 20',
                'description' => 'Description for Product 20',
                'price' => 2000.00,
                'image_path' => 'images/upload/products/20.jpg',
                'brand' => 'Brand 20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
